"""Add knowledge items table

Revision ID: 80c5f9b455f3
Revises: 2d3ebd9a46f5
Create Date: 2025-12-13 12:48:36.537925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c5f9b455f3'
down_revision = '2d3ebd9a46f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_id'), 'knowledge_items', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_topic'), 'knowledge_items', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_items_topic'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###

