import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from openpyxl import Workbook
from typing import List, Dict, Any
import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "../../../data/exports")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def generate_pdf_quotation(quotation_id: int, items: List[Dict[str, Any]], total_cost: float) -> str:
    """Generates a PDF quotation."""
    filename = f"quotation_{quotation_id}_{datetime.datetime.now().strftime('%Y%m%d')}.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    c = canvas.Canvas(filepath, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, f"Construction Quotation #{quotation_id}")
    
    c.setFont("Helvetica", 12)
    c.drawString(100, 730, f"Date: {datetime.date.today()}")
    c.drawString(100, 710, "Generated by: AI Construction Consultant")
    
    y = 650
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Item")
    c.drawString(300, y, "Quantity")
    c.drawString(400, y, "Unit Price")
    c.drawString(500, y, "Total")
    
    y -= 20
    c.setFont("Helvetica", 10)
    
    for item in items:
        name = item.get("name", "Unknown Item")
        # simple truncation
        if len(name) > 40: name = name[:40] + "..."
        qty = item.get("quantity", 1)
        price = item.get("unit_price", 0)
        line_total = qty * price
        
        c.drawString(50, y, name)
        c.drawString(300, y, str(qty))
        c.drawString(400, y, f"{price:.2f}")
        c.drawString(500, y, f"{line_total:.2f}")
        y -= 15
        
        if y < 50:
            c.showPage()
            y = 700
            
    y -= 20
    c.setFont("Helvetica-Bold", 12)
    c.drawString(400, y, "Grand Total:")
    c.drawString(500, y, f"{total_cost:.2f} EGP")
    
    c.save()
    return filepath

def generate_excel_quotation(quotation_id: int, items: List[Dict[str, Any]], total_cost: float) -> str:
    """Generates an Excel quotation."""
    filename = f"quotation_{quotation_id}_{datetime.datetime.now().strftime('%Y%m%d')}.xlsx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Quotation"
    
    ws.append(["Quotation ID", quotation_id])
    ws.append(["Date", datetime.date.today()])
    ws.append([])
    ws.append(["Item Name", "Quantity", "Unit", "Unit Price (EGP)", "Total (EGP)"])
    
    for item in items:
        ws.append([
            item.get("name"),
            item.get("quantity"),
            item.get("unit", "-"),
            item.get("unit_price"),
            item.get("quantity", 0) * item.get("unit_price", 0)
        ])
        
    ws.append([])
    ws.append(["", "", "", "Grand Total", total_cost])
    
    wb.save(filepath)
    return filepath
